version: "3.9"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    build:
      context: .
      dockerfile: configs/compose/postgres/Dockerfile
    container_name: vpn_DB
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vpnAdmin
      - POSTGRES_PASSWORD=Vpnsh00p2023
      - POSTGRES_DB=vpnshopdb
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups

  redis:
    image: redis:alpine
    container_name: vpn_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "8103094S"