services:
  backenddev:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/dev.Dockerfile
    image: djangovpnshop:dev
    pull_policy: never
    container_name: DjangoVPNshop_dev
    restart: always
    working_dir: /app
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: >
      sh -c "
      if [ ! -f .env ]; then
        cp .env.example .env;
      fi &&
      python manage.py runserver 0.0.0.0:8000
      "
